import fs from 'node:fs';
import path from 'node:path';
import { app, BrowserWindow, ipcMain } from 'electron';
import { openDatabase } from './data/Model';
import { createQueries } from './data/Queries';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let dbQueries: ReturnType<typeof createQueries> | null = null;

const DB_NAME = 'songs.sqlite3';

function getDbPath(dbName: string): string {
  // Prefer cwd (project root when running "npm start"), then app path, then relative to main bundle
  const candidates = [
    path.join(process.cwd(), dbName),
    path.join(app.getAppPath(), dbName),
    path.resolve(__dirname, '..', '..', dbName),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  throw new Error(
    `${dbName} not found. Tried: ${candidates.join(', ')}`
  );
}

function getQueries() {
  if (!dbQueries) {
    const dbPath = getDbPath(DB_NAME);
    const db = openDatabase(dbPath);
    dbQueries = createQueries(db);
  }
  return dbQueries;
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 1024,
    height: 768,
    minWidth: 1024,
    minHeight: 768,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// Register IPC handlers for database queries (used by renderer via preload).
ipcMain.handle('db:getSongData', (_event, sourceSkid: number, sourceSequenceNbr: number) => {
  return getQueries().getSongData(Number(sourceSkid), Number(sourceSequenceNbr));
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
